### ISSUE TITLE
hide guide navigation on landing pages

### ISSUE THREAD

**Issue by t4k** [caltechlibrary/libguine#5]
figured out a template/css hack to accomplish this:

```html
<div id="caltechsystem-guide-title">{{guide_title}}</div>
<ul id="caltechsystem-guide-nav">{{guide_nav}}</ul>
```
on the customize guide template form set the guide_title to show on guide homepage only
```css
#caltechsystem-guide-title { display:none }
:not(#caltechsystem-guide-title:empty) + #caltechsystem-guide-nav { display:none }
```
this effectively finds that the guide title `div` is not empty and hides its adjacent sibling
